### ISSUE TITLE
NoSuchMethodError io.mockk.MockKKt.clearMocks

### ISSUE THREAD

**Issue by swhammack** [Ninja-Squad/springmockk#13]
Hi, I'm really glad you wrote this. I've been trying to figure out how to use Mockk with Spring Boot Testing for a bit.

I'm running into this exception after running a test. 
``` 
java.lang.NoSuchMethodError: io.mockk.MockKKt.clearMocks$default(Ljava/lang/Object;[Ljava/lang/Object;ZZZZZILjava/lang/Object;)V
        at com.ninjasquad.springmockk.ClearMocksTestExecutionListener.clearMocks(ClearMocksTestExecutionListener.kt:57)
        at com.ninjasquad.springmockk.ClearMocksTestExecutionListener.clearMocks(ClearMocksTestExecutionListener.kt:43)
        at com.ninjasquad.springmockk.ClearMocksTestExecutionListener.afterTestMethod(ClearMocksTestExecutionListener.kt:37)
        at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443)
        at org.springframework.test.context.junit.jupiter.SpringExtension.afterEach(SpringExtension.java:139)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:218)
```

These are my test dependencies in gradle

```
 testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(module = "junit")
        exclude(module = "mockito-core")
    }
    testImplementation("org.springframework.security:spring-security-test")
    testImplementation("org.testcontainers:testcontainers:1.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.4.0")
    testImplementation("com.ninja-squad:springmockk:1.1.0")
    testImplementation("io.mockk:mockk:1.9")
```

Any idea why this could be happening?

**Comment by jnizet** [comment]
springmockk 1.1.0 depends on mockk 1.9.1. You need to upgrade. My guess is that it will fix the issue.
Please tell, so that I can close the issue, or investigate further.
