### ISSUE TITLE
SpykBean/MockkBean can't be used on same bean in different tests

### ISSUE THREAD

**Issue by laurentverbruggen** [Ninja-Squad/springmockk#25]
I want to mock a bean with the following:

```
@MockkBean
lateinit var bean: SomeBean
```

But if I want to mock that same bean in 2 different tests and duplicate the code above for those tests, I get the following:

```
Caused by: java.lang.IllegalStateException: Duplicate mock definition [MockkDefinition@c2e33 name = [null], typeToMock = <myClass>, extraInterfaces = set[[empty]], clear = AFTER]
	at org.springframework.util.Assert.state(Assert.java:94)
	at com.ninjasquad.springmockk.DefinitionsParser.addDefinition(DefinitionsParser.kt:104)
	at com.ninjasquad.springmockk.DefinitionsParser.parseMockkBeanAnnotation(DefinitionsParser.kt:72)
	at com.ninjasquad.springmockk.DefinitionsParser.parseElement(DefinitionsParser.kt:45)
	at com.ninjasquad.springmockk.DefinitionsParser.access$parseElement(DefinitionsParser.kt:23)
	at com.ninjasquad.springmockk.DefinitionsParser$parse$1.invoke(DefinitionsParser.kt:36)
	at com.ninjasquad.springmockk.DefinitionsParser$parse$1.invoke(DefinitionsParser.kt:23)
	at com.ninjasquad.springmockk.DefinitionsParser$sam$org_springframework_util_ReflectionUtils_FieldCallback$0.doWith(DefinitionsParser.kt)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:731)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
	at com.ninjasquad.springmockk.DefinitionsParser.parse(DefinitionsParser.kt:36)
	at com.ninjasquad.springmockk.MockkPostProcessor.postProcessBeanFactory(MockkPostProcessor.kt:88)
	at com.ninjasquad.springmockk.MockkPostProcessor.postProcessBeanFactory(MockkPostProcessor.kt:78)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 53 common frames omitted
```

Weirdly enough, if I remove the annotation in one of both tests, both tests will have the bean mocked and will succeed. Same thing for SpykBean. Also @SpykBean in one test and @MockkBean in the other results in both tests having a mocked (and not spied) bean.
So I guess annotations are not scoped to the test (which I hope you consider a bug)?

**Comment by jnizet** [comment]
Hi Laurent.

I tried to reproduce your issue, but failed. Here's the repo where I tried: https://github.com/jnizet/demo25.

As you can see, it has three tests. All use MockkBean on SomeBean. The first and second one only mock SomeBean. The third one mocks an additional bean. Running the tests (using `./gradlew test`) shows that they all pass.

So, without being able to reproduce the issue, it's quite hard to understand what might be wrong and what to fix (if there is something to fix).

Please try doing just what I did: provide a **minimal** repo that I can clone and see the bug reproduced.

**Comment by laurentverbruggen** [comment]
I can easily reproduce the issue in my repository but I can't share it here because it is business sensitive. I will try to reproduce it in a minimal repository and get back to you. Thanks for looking into it already.
